version: '3.8'

services:
  # Image 1: SRT Server (replaces your current SRTLA receiver)
  srt-server:
    image: datagutt/belabox-receiver:latest
    container_name: srt-server
    restart: unless-stopped
    ports:
      - "5077:5000/udp"    # SRT ingest (mobile apps send here)
      - "8177:8181/tcp"    # Private stats
      - "8277:8282/udp"    # SRT output (OBS pulls from here)
      - "3077:3000/tcp"    # Public stats (NOALBS uses this)
    volumes:
      - ./config/srtla/config.json:/app/config.json
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - streaming-network

  # Image 2: RTMP Server (uses existing nginx-rtmp image)
  rtmp-server:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935/tcp"    # RTMP server (GoPro/Moblin send here)
      - "8080:8080/tcp"    # RTMP stats
    volumes:
      - ./data/recordings:/recordings
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - streaming-network

  # Image 3: PostgreSQL + Elixir Backend (combined in one image)
  postgres-elixir:
    build: ./containers/postgres-elixir
    container_name: postgres-elixir
    restart: unless-stopped
    ports:
      - "5432:5432"    # PostgreSQL
      - "4000:4000"    # Elixir API
    environment:
      - POSTGRES_DB=streaming_hub
      - POSTGRES_USER=streaming
      - POSTGRES_PASSWORD=streaming_pass_2024
      - DATABASE_URL=postgres://streaming:streaming_pass_2024@localhost:5432/streaming_hub
      - SECRET_KEY_BASE=your_secret_key_change_in_production
      - PHX_HOST=localhost
      - PORT=4000
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./config:/app/config
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge