services:
  # SRT Server - BUILD from local extracted files
  srt-server:
    build:
      context: ./containers
      dockerfile: Dockerfile.srtla-local
    container_name: srt-server-hybrid
    restart: unless-stopped
    
    # PERFORMANCE OPTIMIZATIONS
    mem_limit: 4g
    memswap_limit: 4g
    
    ports:
      - "5077:5000/udp"    # SRTLA ingest
      - "8177:4001/udp"    # SRT ingest/output
      - "8277:8080/tcp"    # HTTP stats
    
    environment:
      - PUID=1000
      - PGID=1000
      
    networks:
      - streaming-network

  # RTMP Server - BUILD from local extracted files
  rtmp-server:
    build:
      context: ./containers
      dockerfile: Dockerfile.nginx-local
    container_name: rtmp-server-hybrid
    restart: unless-stopped
    
    # PERFORMANCE
    mem_limit: 2g
    memswap_limit: 2g
    
    ports:
      - "1935:1935/tcp"    # RTMP server
      - "8080:8080/tcp"    # RTMP stats
      
    volumes:
      - ./data/recordings:/recordings
      - ./config/nginx-optimized.conf:/etc/nginx/nginx.conf
      
    networks:
      - streaming-network

  # Supabase Realtime - LOCAL BUILD (for key management)
  supabase-realtime:
    build: ./containers/postgres-elixir
    container_name: supabase-realtime-local
    restart: unless-stopped
    
    # PERFORMANCE
    mem_limit: 3g
    memswap_limit: 3g
    
    ports:
      - "5433:5432"    # PostgreSQL
      - "4000:4000"    # Realtime API
      
    environment:
      # Database config
      - DATABASE_URL=postgres://realtime:realtime_pass_2024@localhost:5432/realtime_dev
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=realtime
      - DB_PASSWORD=realtime_pass_2024
      - DB_NAME=realtime_dev
      
      # Performance settings
      - ELIXIR_ERL_OPTIONS="+hmax 1000000000"
      - ERL_MAX_PORTS=65536
      
      # Realtime config
      - SECRET_KEY_BASE=your_secret_key_change_in_production_make_it_very_long
      - JWT_SECRET=your_jwt_secret_for_realtime_auth
      - PORT=4000
      - PHX_HOST=localhost
      - PHX_SERVER=true
      
      # Streaming hub config - FOR KEY MANAGEMENT
      - ENABLE_CAMERA_MANAGEMENT=true
      - SRT_STATS_URL=http://srt-server:8080/stats
      - RTMP_STATS_URL=http://rtmp-server:8080/stat
      
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/realtime:/app/data
      - /dev/shm:/dev/shm:rw
      
    depends_on:
      - srt-server
      - rtmp-server
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge