version: '3.8'

services:
  # Image 1: SRT Server (your mobile streams)
  srt-server:
    image: datagutt/belabox-receiver:latest
    container_name: srt-server
    restart: unless-stopped
    ports:
      - "5077:5000/udp"    # SRT ingest (mobile apps send here)
      - "8177:8181/tcp"    # Private stats
      - "8277:8282/udp"    # SRT output (OBS pulls from here) 
      - "3077:3000/tcp"    # Public stats (NOALBS uses this)
    volumes:
      - ./config/srtla/config.json:/app/config.json
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - streaming-network

  # Image 2: RTMP Server (your GoPro/desktop streams)
  rtmp-server:
    image: tiangolo/nginx-rtmp:latest
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935/tcp"    # RTMP server (GoPro/Moblin send here)
      - "8080:8080/tcp"    # RTMP stats
    volumes:
      - ./data/recordings:/recordings
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - streaming-network

  # Image 3: Supabase Realtime (PostgreSQL + Real-time streaming management)
  supabase-realtime:
    build: ./containers/postgres-elixir
    container_name: supabase-realtime
    restart: unless-stopped
    ports:
      - "5433:5432"    # PostgreSQL (CHANGED: was 5432, now 5433)
      - "4000:4000"    # Realtime API + WebSocket
    environment:
      # Database config - KEEP INTERNAL PORT AS 5432
      - DATABASE_URL=postgres://realtime:realtime_pass_2024@localhost:5432/realtime_dev
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=realtime
      - DB_PASSWORD=realtime_pass_2024
      - DB_NAME=realtime_dev
      
      # Realtime config
      - SECRET_KEY_BASE=your_secret_key_change_in_production_make_it_very_long
      - JWT_SECRET=your_jwt_secret_for_realtime_auth
      - PORT=4000
      - PHX_HOST=localhost
      - PHX_SERVER=true
      
      # Streaming hub config
      - ENABLE_CAMERA_MANAGEMENT=true
      - SRT_STATS_URL=http://srt-server:3000/stats
      - RTMP_STATS_URL=http://rtmp-server:8080/stat
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/realtime:/app/data
    depends_on:
      - srt-server
      - rtmp-server
    networks:
      - streaming-network

networks:
  streaming-network:
    driver: bridge